[input]
	bam = "input_chr19_gene_tags.bam"
	source.mode = "bam_tag"
    source.tag = 'XF'


[umi]
	strategy.kind = "unique"
	bucket = "PerPosition"

[umi.extract]
    mode = "regex_name"
    regex = ":(UMI_[AGTC]+):"

[strategy]
	direction = 'ignore'


[output]
	directory = 'output'
	write_annotated_bam  = true



