[input]
	bam = "input_chr19_gene_tags.bam"
	source.mode = "bam_tag"
    source.tag = 'XF'


[umi]
    mode = "regex_name"
    regex = ":(UMI_[AGTC]+):"

[strategy]
	direction = 'ignore'

[dedup]
	mode = "umi"
	umi_grouping = "unique"


[output]
	directory = 'output'
	write_annotated_bam  = true



