# we dedup per position.
# and the output we want to compare with is a sam file
[input]
	bam = "input_chr19.bam"
	correct_reads_for_clipping = true # since this is umi-tools


[input.source]
   mode ="bam_references"

[umi]
	bucket ='PerPosition'
	strategy.kind = "directional"
	strategy.max_distance = 1

[umi.extract]
    mode = "SearchInName"
	search = "_"
	skip = 0
	length = 5

[output]
	directory = 'output'
	mode = 'none'
	write_annotated_bam  = true
	# counts = false TODO



