# a basic reproduction of samtools idxstats

[input]
    bam = "input.bam"

[input.source]
	mode = "gtf"
    filename = "input.gtf"
    feature = 'contig'
    id_attribute = 'contig_id'
    aggr_id_attribute = 'contig_id'

[[filter]]
    mode = "multimapper"
    action = "remove"


[strategy]
	multi_region = 'count_both'
	direction = 'reverse'

[quant]
   mode = "basic"

[output]
   directory = "output"
