
[input]
    bam = "input.bam"
	correct_reads_for_clipping = false # starsolo doesn't, so we don't either.

[input.source]
   mode ="bam_references"

[cell_barcodes]
	extract = {mode = "Tag", tag = 'CB'}
    separator_char = '_'
	max_hamming = 0

[umi]
	mode = 'Tag'
	tag = 'UB'

[strategy]
	multi_region = 'count_both'
	overlap ='intersection_strict'
	direction = 'Forward'

[dedup]
   mode = "sc"
   umi_grouping = 'unique'
   bucket = 'PerReference'

[output]
    directory = 'quant'
    write_annotated_bam = false
