[input]
	bam = "umitools_dedup.bam"

[input.source]
   mode ="gtf"
   filename = "../input.gtf.gz"
   feature = 'exon'
   id_attribute = 'gene_id'
   aggr_id_attribute = 'gene_id'



[[filter]]
	mode = "non_primary"
	action = "remove"

[dedup]
	mode = "none"
	direction = 'forward'


[output]
	directory = 'output'
	write_annotated_bam=true



