[input]
	bam = "input.bam"


[input.source]
   mode ="gtf"
   filename = "input.gtf.gz"
   feature = 'exon'
   id_attribute = 'gene_id'
   aggr_id_attribute = 'gene_id'

[umi]
    mode = "read_region"
	start = 0
	stop = 6

[[filter]]
	mode = "non_primary"
	action = "remove"

# strategy.direction ='forward' is standard

[dedup]
	mode = "umi"
	umi_grouping = "unique"


[output]
	directory = 'output'
#write_annotated_bam  = true



