# a basic reproduction of samtools idxstats
[input]
	bam = "input.bam"
	gtf = "input.gtf.gz"

[[filter]]
	mode = "multimapper"
	action = "remove"

[quant]
   mode = "gtf_stranded"
   feature = 'gene'
   id_attribute = 'gene_id'
   direction = 'forward'


[output]
	directory = "output"
