# a basic reproduction of samtools idxstats
[input]
	bam = "input.bam"
	gtf = "input.gtf.gz"

[quant]
   mode = "featurecounts"
   feature = 'gene'
   id_attribute = 'gene_id'


[output]
	directory = "output"
