# non-unique=all does not *count* multi mappers
# for the features, no matter what the documentation of htseq says
# "-nonunique all [...]
# (Also, if the read (or read pair) aligns to more than one location in the reference, it is scored as alignment_not_unique and also separately for each location.)"
# it just lists them as __alignment_non_unique.
# so we need to filter them.

# (and neither does non_unique fraction work for multi-mapping reads...)
[input]
    bam = "input.bam"

[input.source]
   mode ="gtf"
   filename = "input.gtf.gz"
   feature = 'exon'
   id_attribute = 'gene_id'
   aggr_id_attribute = 'gene_id'
   duplicate_handling= 'collapse'

[[filter]]
	mode = 'multimapper'
	action ='remove'


[strategy]
	direction = 'forward' # as is htseq default
	overlap = 'intersection_non_empty'
    multi_region = 'count_both'

[quant]
   mode = "basic"

[output]
    directory = 'output'
    only_correct = true
    write_annotated_bam = false
