# a basic reproduction of samtools idxstats

[input]
    bam = "input.bam"

[input.source]
	type = "gtf"
    filename = "input.gtf"
    feature = 'contig'
    id_attribute = 'contig_id'
    aggr_feature = 'contig'
    aggr_id_attribute = 'contig_id'

[[filter]]
    mode = "multimapper"
    action = "remove"

[quant]
   mode = "stranded_basic"
   direction ='Reverse'

[output]
   directory = "output"
