[input]
	bam = "input_chr19_gene_tags.bam"
	source.type = "bam_tag"
    source.tag = 'XF'


[quant]
	mode = "unstranded_umi"
    umi_extraction.type = "regex_name"
    umi_extraction.regex = ":(UMI_[AGTC]+):"
	umi_grouping = "unique"


[output]
	directory = 'output'
	write_annotated_bam  = true



