[input]
	bam = "input_chr19_gene_tags.bam"
	source.type = "bam_tag"
    source.tag = 'XF'


[umi]
    type = "regex_name"
    regex = ":(UMI_[AGTC]+):"

[quant]
	mode = "unstranded_umi"
	umi_grouping = "unique"


[output]
	directory = 'output'
	write_annotated_bam  = true



