[input]
    bam = "input.bam"

[input.source]
   type ="gtf"
   filename = "input.gtf.gz"
   feature = 'exon'
   id_attribute = 'gene_id'
   aggr_id_attribute = 'gene_id'
   duplicate_handling= 'collapse'

[[filter]]
	mode = 'multimapper'
	action ='remove'


[strategy]
	direction = 'forward' # as is htseq default
	overlap = 'intersection_non_empty'
    multi_region = 'drop'

[quant]
   mode = "basic"

[output]
    directory = 'output'
    only_correct = true
    write_annotated_bam = false
