# a basic reproduction of samtools idxstats
[input]
    bam = "input.bam"

[input.source]
	type = "gtf"
    filename = "input.gtf"
    feature = 'contig'
    id_attribute = 'contig_id'
    aggr_id_attribute = 'contig_id'

[[filter]]
    mode = "multimapper"
    action = "remove"

[quant]
   mode = "unstranded_basic"


[output]
    directory = "output"
    write_annotated_bam=false
