[input]
    bam = "input.bam"

[input.source]
   type ="gtf"
   filename = "input.gtf.gz"
   feature = 'exon'
   id_attribute = 'gene_id'
   aggr_feature = 'gene'
   aggr_id_attribute = 'gene_id'
   duplicate_handling= 'collapse'


[[filter]]
    mode = "multimapper"
    action = "remove"


[quant]
   mode = "unstranded_featurecounts"

[output]
    directory = 'output'
    write_annotated_bam = false
