[input]
    bam = "input.bam"

[input.source]
   mode ="gtf"
   filename = "input.gtf.gz"
   feature = 'exon'
   id_attribute = 'exon_id'
   aggr_id_attribute = 'exon_id'
   duplicate_handling= 'rename'


[[filter]]
    mode = "multimapper"
    action = "remove"

[strategy]
	multi_region = 'drop'
	direction = 'ignore'

[dedup]
   mode = "none"

[output]
    directory = 'output'
    write_annotated_bam = false
