# a basic reproduction of samtools idxstats
[input]
	bam = "input.bam"

[input.source]
	type = "bam_references"

[strategy]
	direction = 'ignore'

[quantification]
   mode = "basic"


[output]
	directory = 'output'
