# a basic reproduction of samtools idxstats
[input]
	bam = "input.bam"
	gtf = "input.gtf.gz"

[quant]
   mode = "gtf_unstranded"
   feature = 'contig'
   id_attribute = 'contig_id'
	split_feature = 'contig'
   split_id_attribute = 'contig_id'


[output]
	directory = "output"
